---
- name: Install nginx
  dnf:
    name: nginx
    state: latest
    update_cache: true
  
- name: Enable and start nginx
  systemd: 
    name: nginx
    enabled: yes
    state: started

- name: alllow port 80
  firewalld:
    port: "80/tcp"
    zone: public
    state: enabled
    permanent: true
  notify:
    - firewalld_reload
- meta: flush_handlers
